AllCops:
  NewCops: enable

Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 99

Metrics/ClassLength:
  Description: 'Avoid classes longer than 1000 lines of code.'
  Enabled: true
  VersionAdded: '0.25'
  VersionChanged: '0.87'
  CountComments: false  # count full line comments?
  Max: 1000
  CountAsOne: []

Metrics/AbcSize:
  Enabled: false